jobs:
- job: 'Ubuntu1604'
  pool:
    name: 'Azure Pipelines'
    vmImage: 'ubuntu-16.04'
  steps:
  - template: src/bash/templates/basic-execution.yml
  - template: src/bash/templates/ubuntu-specific-case.yml

- job: 'Ubuntu1804'
  pool:
    name: 'Azure Pipelines'
    vmImage: 'ubuntu-18.04' 
  steps:
  - template: src/bash/templates/basic-execution.yml
  - template: src/bash/templates/ubuntu-specific-case.yml

- job: 'Ubuntu2004'
  pool:
    name: 'Azure Pipelines'
    vmImage: 'ubuntu-20.04'
  steps:
  - template: src/bash/templates/basic-execution.yml
  - template: src/bash/templates/ubuntu-specific-case.yml
